// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPyoxWSNqxOrz-9HveMn9vnRwdMEr_xFk',
    appId: '1:114629043612:web:db32effcd19c14dc6ad459',
    messagingSenderId: '114629043612',
    projectId: 'profilemate-9e1e0',
    authDomain: 'profilemate-9e1e0.firebaseapp.com',
    storageBucket: 'profilemate-9e1e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd43kzvaymGivTD2C4dISOuTKfkE_FHM0',
    appId: '1:114629043612:android:fd40950f253d21e96ad459',
    messagingSenderId: '114629043612',
    projectId: 'profilemate-9e1e0',
    storageBucket: 'profilemate-9e1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2O4vmmqyPRlINht_-HLaXDFvxugwnjxA',
    appId: '1:114629043612:ios:55892a42198681086ad459',
    messagingSenderId: '114629043612',
    projectId: 'profilemate-9e1e0',
    storageBucket: 'profilemate-9e1e0.firebasestorage.app',
    iosBundleId: 'com.example.userProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2O4vmmqyPRlINht_-HLaXDFvxugwnjxA',
    appId: '1:114629043612:ios:55892a42198681086ad459',
    messagingSenderId: '114629043612',
    projectId: 'profilemate-9e1e0',
    storageBucket: 'profilemate-9e1e0.firebasestorage.app',
    iosBundleId: 'com.example.userProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPyoxWSNqxOrz-9HveMn9vnRwdMEr_xFk',
    appId: '1:114629043612:web:d214931bcaf8da1b6ad459',
    messagingSenderId: '114629043612',
    projectId: 'profilemate-9e1e0',
    authDomain: 'profilemate-9e1e0.firebaseapp.com',
    storageBucket: 'profilemate-9e1e0.firebasestorage.app',
  );

}